[tool.poetry]
name = "template-repository-python"
version = "0.1.0"
description = ""
authors = ["Kazuto Makino"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
autopep8 = "^2.0.4"
pyproject-flake8 = "^6.0.0.post1"
isort = "^5.12.0"
jupyterlab = "^4.0.5"
pre-commit = "^3.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
